### ISSUE TITLE
Default python interrupter path if not set

### ISSUE THREAD

**Issue by engineering-matters** [Mahlet-Inc/hobbits#1]
If it's not set, could be nice to have the python interrupter for the Python Runner auto-populate if python can be found on the system path. Perhaps a drop down if multiple versions are available.

**Comment by hello-adam** [comment]
I think simply preferring python3 to python when searching the path and allowing a dumb override is the best way to handle this.  Trying to determine the available versions and having a convenient dropdown seems too "smart".
