### ISSUE TITLE
KSC warnings are perceived as errors

### ISSUE THREAD

**Issue by KOLANICH** [Mahlet-Inc/hobbits#102]
Such unneeded and undisableable warnings as violations of the badly-designed style guide.

**Comment by hello-adam** [comment]
Are you talking about the kaitai plugin naively printing ksc output? What style guide are you referring to?

**Comment by KOLANICH** [comment]
Latest (nightly) versions of KSC contain a built-in linter that emits warnings when a creator of a spec has violated [the style guide](https://github.com/kaitai-io/kaitai_struct_doc/blob/master/ksy_style_guide.adoc).

**Comment by hello-adam** [comment]
Ah, ok, you're saying that if there's stderr output from KSC, the hobbits plugin should not bomb out (it should wait to see if there is a generated ".py" parser file.)

**Comment by KOLANICH** [comment]
Why not to use the information in JSON form?

**Comment by hello-adam** [comment]
can you give an example of the `--ksc-json-output` JSON output that has the warning in a section that will be distinct from errors? Maybe also an example of how failure condition errors will look?

**Comment by KOLANICH** [comment]
Currently it doesn't emit any warnings into JSON repr at all.
Errors look like:

```json
{"./lto.ksy": {"errors": [{"file": "./lto.ksy","path": ["seq","8"],"message": "string type, but no encoding found"}]}}
```

**Comment by hello-adam** [comment]
let me know if b2fafbf solves this for you. I was able to test with error and non-error conditions, but I don't have a nightly build of ksc to test the warning situation (also, I'm not sure how robust my parsing of the errors is...)

**Comment by KOLANICH** [comment]
Yeah, that works. I had to rebase it over `master` though because `devel` is still broken - it doesn't detect plugins properly.
