### ISSUE TITLE
Cannot analyse the extracted blob with KS

### ISSUE THREAD

**Issue by KOLANICH** [Mahlet-Inc/hobbits#109]
Even the simpest spec consuming 1 byte fails: `EOFError: requested 1 bytes, but got only 0 bytes`.

**Comment by hello-adam** [comment]
just to be clear, this is if you do Kaitai Struct -> Extractor and then try to run Kaitai Struct on the extracted bytes? I just ran Kaitai Struct on a PNG, ran the Extractor on everything (i.e. I selected the "magic" section checked the "Extract Section" and "Extract After Section" boxes), and then was able to successfully  run the PNG parser on that extracted container.

**Comment by KOLANICH** [comment]
>just to be clear, this is if you do Kaitai Struct -> Extractor and then try to run Kaitai Struct on the extracted bytes?

Correct.

**Comment by hello-adam** [comment]
as I mentioned, I can't reproduce this. Are you checking the "Extract Section" box in the Extractor plugin?

**Comment by KOLANICH** [comment]
Yes.

[Here is the spec](https://github.com/KOLANICH/kaitai_struct_formats/blob/lto/hardware/GPS/lto.ksy), the file can be downloaded [from here](https://gllto.glpals.com/2day/v2/latest/lto2.dat) (or fetched from a phone with a Broadcom GPS chipset), the extracted subframe is from `unkn2[any].payload`. Width framer works (though the results are completely uninformative, but some experimentation made me beleive that the width is 6, though it may be a red herring), but none of KS specs. I had to use python to extract the payloads and save them to a dedicated file (though width framer results are still uninformative, likely the payloads are compressed or scrambled or encrypted, the contents of the payloads is unknown, it is likely the ephemeris are in `unkn6` rather than `unkn2`, since 64 = 2 * 32, where 32 is the count of GPS sats ).

**Comment by hello-adam** [comment]
Cool, I will try to take a look at this soon

**Comment by hello-adam** [comment]
![payload-extracted](https://user-images.githubusercontent.com/60397633/130334345-80f7eeb6-10f9-4cf0-9992-7a6b89fcc347.png)

I was able to extract that payload section - are you saying the kaitai plugin fails to analyze the extracted part? what spec should I use to reproduce that?

**Comment by hello-adam** [comment]
I made some improvements in the develop branch - let me know if any of that works better for you.

**Comment by KOLANICH** [comment]
Now I get 
```
Analyzer Plugin Error: Plugin 'Kaitai Struct' reported an error with its processing: Failure Running parser in Python:
Python stderr:
Traceback (most recent call last):
  File "/tmp/HobbitsPythontzXFus/thescript.py", line 162, in parse_data
    target._read()
  File "/tmp/hobbits-KLwkoQ/lto.py", line 79, in _read
MemoryError
```
when trying to analyse a simple test spec for a child bit-container

```yaml
meta:
  id: a
seq:
  - id: a
    type: u1
```

(Must be loaded from a file, the spec written manually into the text box is not used, instead the previously-compiled one is)

**Comment by hello-adam** [comment]
Yeah, I noticed that yesterday and forgot. A new file is written and a new temporary directory is created, so I couldn't figure out why it would do this. Thinking about it again, I bet the hobbits internal python stuff needs to unload the previously loaded module of the same name. It won't be reused if you change the id. I should be able to fix the re-use behavior.

Aside from the re-use error, is there another error? Are you getting unexpected errors even after changing the id?

**Comment by KOLANICH** [comment]
>I bet the hobbits internal python stuff needs to unload the previously loaded module of the same name.

Thank for the hint, it is really this. #122

**Comment by hello-adam** [comment]
cool, thanks, that's what I was going to do. I'll start pondering ways to make this better.

**Comment by KOLANICH** [comment]
Thank you for implementing this and other features.
