### ISSUE TITLE
Copying hex from hex viewer

### ISSUE THREAD

**Issue by radio-satellites** [Mahlet-Inc/hobbits#154]
Hello,

Thank you very much for the wonderful software!

I was wondering, how do I copy to clipboard from the hex editor? I can't seem to select anything. 

![image](https://user-images.githubusercontent.com/114111180/202863968-f94a926e-ac87-4f98-9c02-3ae73510f5f9.png)

**Comment by hello-adam** [comment]
Unfortunately, there isn't an easy way to do that. The closest option is exporting the entire file as hex text (File -> Export Bits To -> Hex String). @wetBadger was working on a plugin to make it easier to edit and extract chunks of hex, but it hasn't been merged yet.

**Comment by hello-adam** [comment]
#118 was added in February (sorry for the delay) - copying via the edit plugin is probably the closest this will get to being resolved
