### ISSUE TITLE
Numbers in Width Framer increase until they hit NaN

### ISSUE THREAD

**Issue by tkzv** [Mahlet-Inc/hobbits#17]
1. Start Hobbits.
2. Import any binary file. (I used an uncompressed bitmap or a ZIP.)
3. Open "Width Framer" tab and "List" tab.
4. Enter any number for Width.
5. Press "Analyze" several times. With each press the correlation coefficients increase — their order of magnitude doubles, until they reach ~1e+214 ant then "nan".

This is clearly wrong.

Observed for version 0.22.0 in Ubuntu Linux.

**Comment by hello-adam** [comment]
yeah, this one has been there for a while and I haven't gotten around to it (it's on our internal bug tracker and I forgot to transfer it out here.)

your timing might be good because I think I'll have time to look into this today

**Comment by hello-adam** [comment]
your description of the bug helped me find a solution pretty quickly, thank you!

I should have 362f27b7f1e20f9820299d71bb89f3155f134b54 merged in and 0.22.1 released in a  few minutes
