### ISSUE TITLE
Byte Raster makes interface unresponsive

### ISSUE THREAD

**Issue by tkzv** [Mahlet-Inc/hobbits#19]
When "Byte Raster" tab is selected, and the image is over 100 pixels wide, the interface responds to user actions much slower. On my 2-core 2GHz Celeron when a 160x160 image is displayed, switching between other visualization tabs takes negligible time, but switching to and from "Byte Raster" takes between 2 and 3 seconds. Changing its zoom takes about 5 seconds. Other user actions are processed about as slowly.

Is there any way to make the interface faster when "Byte Raster" is visible?

Observed in Ubuntu Linux for versions 0.22.0 and 0.22.1.

**Comment by hello-adam** [comment]
The current painting of the display is pretty simple and "naive" performance-wise, so there are definitely some untapped improvements I could experiment with.

Locking up the interface is definitely bad, and 5 seconds is kind of insane.
