### ISSUE TITLE
Use more symbols in ASCII view

### ISSUE THREAD

**Issue by tkzv** [Mahlet-Inc/hobbits#20]
Currently, ASCII view seems to replace symbols below 32 and above 126 with dots. But if Hobbits' ASCII tab behaves more like Hiew, more information would be available to the user. For example, it could display symbols from an 8-bit code page for 128-255 and glyphs similar to IBM control symbols for 0-31 and 127. Here are symbol set examples for code pages 437 and 866: https://en.wikipedia.org/wiki/File:Codepage-437.png https://en.wikipedia.org/wiki/File:Octets_in_conformant_CP866_ordered_by_nibbles.png

**Comment by hello-adam** [comment]
Yeah, I could definitely add a dropdown or checkbox to enable more symbols.  I'll probably keep the current mode as well because sometimes it's nice for the ASCII Latin characters to "pop" a little bit from the noise.
