### ISSUE TITLE
Implementation improvements for Kaitai Struct Plugin

### ISSUE THREAD

**Issue by hello-adam** [Mahlet-Inc/hobbits#24]
Kaitai is a declarative language for parsing binary formats.  We need plugins that will:
 - compile and run the kaitai parser on a bitcontainer (using python?)
 - display the parsed information kind of like kaitai Web IDE
 - easily allow blobs to be broken off into their own bitcontainers for further isolated analysis

https://kaitai.io/

@KOLANICH

**Comment by KOLANICH** [comment]
Moved from https://github.com/Mahlet-Inc/hobbits/issues/13#issuecomment-597840759

So the plan is following:
1. #23
2. the interpreter will load my script
3. the script will create a Qt text editor window.
4. the script is going to interact to Kaitai Struct compiler to compile specs from the text editor using my kaitaiStructCompile lib, transforming them into python sources
5. the script will eval the sources, the results will be called against the blobs, the result of that are ASTs and offsets of boundaries of each block
6. using the API injected by hobbits the script is going to pass this info to hobbits

**Comment by hello-adam** [comment]
OK, here's my summary of the plan (mostly repeating for clarity's sake):
 1. an operator plugin with a text editor for entering a kaitai struct. this plugin would have your C-based kaitai struct compiler (?) and a python interpreter in it for the kaitai struct runtime.
 2. some python interface would need to be created to pass hobbits bitcontainers in and out of python. in the long-term, this could be a core library feature, but we can keep it to this plugin at first
 3. some embedded python code would use the hobbits python interface, the kaitai struct runtime, and the generated kaitai python spec to create a marked-up hobbits bitcontainer (this can be done with the current metadata system, but it might prompt some refactoring/extending of that)

I think it would be good to make a simpler version first that works a lot like the current PythonRunner.  It could use any installed interpreter and kaitai struct compiler as well as the current JSON interface to pass the data between Python and hobbits. I could probably make this very quickly.  The sooner I have this, the sooner I will understand how different parts of hobbits (like the displays and the container metadata) need to be altered in order to support a katai web IDE-like experience.

**Comment by hello-adam** [comment]
it's also worth bringing up that this project is under a more permissive license (MIT) than kaitai (GPLv3). Any plugin that integrates code from kaitai (like the python runtime) would need to be maintained in a separate repository as GPLv3 code for license simplicity, but could still be included as a core plugin in packages.

**Comment by KOLANICH** [comment]
>this plugin would have your C-based kaitai struct compiler (?) and a python interpreter in it for the kaitai struct runtime.

Not quite. KSC itself is written in Scala. It generates parsers in multiple languages, including C++, rust, JS, python, lua. Compiled languages are out of scope - they require large compilers and there may be problems with runtime libs. Since we already have a python plugin, I guess we gonna extend it.

>some python interface would need to be created to pass hobbits bitcontainers 
 in and out of python.

only in.

>some embedded python code would use the hobbits python interface, the kaitai struct runtime, and the generated kaitai python spec to create a marked-up hobbits bitcontainer (this can be done with the current metadata system, but it might prompt some refactoring/extending of that)

>I think it would be good to make a simpler version first that works a lot like the current PythonRunner.

Yes, I even have an another script you can repurpose for that: https://gitlab.com/KOLANICH/kaitai2WxHexEditor.py

>It could use any installed interpreter and kaitai struct compiler as well as the current JSON interface to pass the data between Python and hobbits.

If you want to keep separation between interpreter and hobbits, here are the following thing IMHO should be done:
1. stop embeding the script into an interpreter. It must be a package.
2. make it possible to change the interpreter. It not necessarily must be python. Any binary following the protocol should fit. python, JS, C++, java - everything can be connected like this.
3. stop using files. Instead shared memory mappings can be used.
2. stop using JSON. json is VERY inefficient. We can use an own binary format and protocol. It doesn't need to be complicated. Basically we need 3 independent communication channels, all are memory mappings, but different ones. One represents the whole file under analysis. Another ones are ring buffers used for signalling.  Basically there is a header containing offsets of head and tail and sync primitives and the rest of the mapping is occupied by data.  We can append there messages. Messages are tightly packed raw C structs.

**Comment by KOLANICH** [comment]
>it's also worth bringing up that this project is under a more permissive license (MIT) than kaitai (GPLv3).

Yeah, I have already encountered this. See https://github.com/kaitai-io/kaitai_struct/issues/466

**Comment by hello-adam** [comment]
I made some progress towards a prototype kaitai struct plugin: https://github.com/Mahlet-Inc/hobbits/tree/24-kaitai-struct-plugin

It works, but you need the id field in your ksy to be "custom".  It has a ways to go, but I wanted to get a quick and dirty solution so that I could start experimenting with changes to the display plugin and bit container metadata that would be able to take full advantage of the kind of information that kaitai would be providing.

**Comment by hello-adam** [comment]
Here's the current state of this plugin: https://youtu.be/RIACHS5HEuE

I realize there are some implementation details that can improve, but I think that feature-wise the plugin is pretty good right now.  I'm going to change the name of this issue to reflect that it's more about implementation goals at this point (since there's already discussion about that here)

**Comment by XVilka** [comment]
It's possible to use Kaitai compiler implementation in Go though, so linking with C++ will be possible: https://github.com/draffensperger/go-interlang

**Comment by hello-adam** [comment]
too bad the Go compiler only outputs Go files. those would need to be compiled before they could be loaded. (unless I'm misunderstanding something?)

I think what I really want is a C, Python, or Go kaitai struct compiler implementation that can output Python parsers. I wonder if that Go implementation could be easily modified to do that...

**Comment by hello-adam** [comment]
for future reference: https://github.com/cugu/kaitaigo

**Comment by KOLANICH** [comment]
What's wrong with the reference one running over JVM?

**Comment by hello-adam** [comment]
The reference one works fine, it's just that the user needs to have the right version installed. Maybe I'll pre-parse all of the "built-in" ksy files so that a novice doesn't even need ksc installed. If someone is writing custom ksy specs, then they will need ksc installed.

**Comment by hello-adam** [comment]
I added pre-compiled python ksy's a little while ago, so now the simplest case works without any external dependencies.  There's a few stability/functionality issues with some of the specs, but I'll try to just document and fix those on a case-by-case basis.
