### ISSUE TITLE
Use symbolic or hard links in Linux distribution archives

### ISSUE THREAD

**Issue by tkzv** [Mahlet-Inc/hobbits#25]
The largest component of Linux distribution is lib/ directory, which contains 3 or 4 files of each shared library under different names, e.g *.so, *.so.5, *.so.5.6, *.so.5.6.1. Those files are identical, but each takes separate space on disk. And since most of them are too big for gzip to detect their identity, they take separate space in the archive. Replacing them with hard or symbolic links will work the same, but make the binary package almost 4 times smaller and easier to download.

**Comment by hello-adam** [comment]
I fixed this, but I think I messed up the release.  The changes will be present in the next successful release.
