### ISSUE TITLE
Create a wizard_installer batch file to simplify development on Windows

### ISSUE THREAD

**Issue by nfi002** [Mahlet-Inc/hobbits#49]

**Comment by nfi002** [comment]
Since the [wizard_installer.sh](https://github.com/Mahlet-Inc/hobbits/blob/master/wizards/wizard_installer.sh) file in the wizards directory is for Linux users, Windows users can create a batch file called wizard_installer in the wizards directory and paste the code from the [wizard_installer.bat](https://github.com/nfi002/hobbits/blob/new-plugin/wizards/wizard_installer.bat) file  in it. Run [wizard_installer.bat](https://github.com/nfi002/hobbits/blob/new-plugin/wizards/wizard_installer.bat) from inside the wizards directory to add Hobbits Plugin Qt Creator templates (restart Qt Creator after doing this).

**Comment by hello-adam** [comment]
Thank you for opening and resolving this @nfi002 !
