### ISSUE TITLE
Add view descriptions

### ISSUE THREAD

**Issue by mahlet-liam** [Mahlet-Inc/hobbits#63]
As hobbits expands to support more than just digital data streams, it would be good to have short descriptions for each of the views so people new to the tool or new to using a particular view can quickly and easily know what information that view is attempting to display. These descriptions can take many forms:

- Additions to the external docs
- In-application Help docs
- Static short descriptions as part of the view panel
- Short descriptions as a mouseover/hover over text popup
- Short descriptions as part of a "help key" + click

**Comment by hello-adam** [comment]
I think I'll scope this issue to the addition of a description (and maybe a docs) field to the plugin API, and then something in the GUI that uses that field to provide tooltips. I'm about to make some interface changes for something else, so I'll throw the description thing in while I'm at it.

**Comment by hello-adam** [comment]
the API supports this now, so the GUI just needs a way of activating the tooltip

**Comment by hello-adam** [comment]
7c3bec2 takes care of this (will be in 0.48.0+)
