### ISSUE TITLE
[Bug Report] Program Crashes When Using Kaitai Struct to Analyze BMP and PNG

### ISSUE THREAD

**Issue by CooperW824** [Mahlet-Inc/hobbits#85]
When I use the Kaitai Struct analyzer plugin on PNGs or BMPs the program closes (I presume it's crashing) with no error messages.
I'm using the pre-built binary for Windows.

**Comment by hello-adam** [comment]
Thank you for reporting!

Yeah, it shouldn't do that. I am in the process of refactoring the build system, and there should be a few fixes in that once I finish (should be release 0.45.0), but I will test this scenario on windows before making that release.

Does the Linux one work for you?

**Comment by CooperW824** [comment]
Yeah analyzer in the Ubuntu based release works on BMPs and PNGs, but I'm still running into reliability issues when using it, it seems like the program crashes randomly when I click the arrow buttons to cycle through selections, and then other times it works fine. When the program does crash, I do get some error messages output to the terminal those can be found below. 

```
:~/Downloads/Hobbits/bin$ ./hobbits
malloc(): unsorted double linked list corrupted
Aborted (core dumped)
:~/Downloads/Hobbits/bin$ ./hobbits
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
:~/Downloads/Hobbits/bin$ ./hobbits
Type conversion already registered from type QSharedPointer<BitContainerPreview> to type QObject*
malloc(): unsorted double linked list corrupted
Aborted (core dumped)
```

**Comment by hello-adam** [comment]
Did this get any better in 0.46.2? I found a bug that could have been doing this, but it might have been something separate.

**Comment by hello-adam** [comment]
hmm, I accidentally auto-closed this with the way I wrote the commit. *0.46.3* definitely fixed a crash that behaved like that. Please re-open the issue if you can still reproduce the crash in 0.46.3
