### ISSUE TITLE
For latest release links to win and mac contains wrong file name

### ISSUE THREAD

**Issue by lupin-de-mid** [Mahlet-Inc/hobbits#94]
https://github.com/Mahlet-Inc/hobbits/releases/tag/v0.46.3

win link - https://github.com/Mahlet-Inc/hobbits/releases/download/v0.46.3/hobbits-0.46.3-mac.txz
mac link - https://github.com/Mahlet-Inc/hobbits/releases/download/v0.46.3/hobbits-0.46.3-win.txz

**Comment by hello-adam** [comment]
Thank you! Fixed in 0.46.4
