### ISSUE TITLE
[windows] Application crashes if "Split view" is applied after loading a file (import menu)

### ISSUE THREAD

**Issue by SFX72** [Mahlet-Inc/hobbits#99]
Hi,

I detect a problem when the "split view" is applied after 'import' file or data -> the application crashes ; 
the "split view" is possible only before 'import', add other view crashes application after 'import'. 

i m using pre-built binaries v0.46.7 (Hobbits (64-bit Windows 2016 msvc2017), Same issue with v0.46.4.
Tested under 2 x Windows 10 pro 64-bit (20H2 & 2004).

Have you already observed this ?

Thanks
Best regards

**Comment by hello-adam** [comment]
ok, confirmed, I will try to set up a debug environment (unfortunately the windows and mac builds are frequently neglected)

**Comment by SFX72** [comment]
Thank you for your reply.

Windows environment sometimes reacts differently. 

Just a live idea : will it be possible in future versions to perform horizontal and/or vertical split views ?
it can be interesting and sometimes different to compare horizontally ; 

Best regards

**Comment by hello-adam** [comment]
yeah, that should be pretty easy to do. Another thing that is needed is saving the tab of the last view (which is especially useful if you have multiple views in a preferred configuration.) I will make a new issue for that.

**Comment by hello-adam** [comment]
added issue #100 for the view splitting

**Comment by hello-adam** [comment]
Alright, this is fixed in 0.46.8 (which is building now and will be available in the next 20 minutes or so)
